### ISSUE TITLE
Support arcs as well as Bezier curves

### ISSUE THREAD

**Issue by orenbenkiki** [dbrgn/svg2polylines#19]
The current implementation doesn't support arcs ("Unsupported path segment: EllipticalArc"), something that's required by my application :-(

**Comment by dbrgn** [comment]
I assume that an elliptical arc can be transformed losslessly to a bezier curve somehow? In that case it should be fairly easy to add.

Contributions are welcome.

**Comment by orenbenkiki** [comment]
Not losslesly, but they can be approximated: https://www.blog.akhil.cc/ellipse
https://mortoray.com/2017/02/16/rendering-an-svg-elliptical-arc-as-bezier-curves/
Etc.

**Comment by orenbenkiki** [comment]
For the special case of an arc of a circle, it is simpler to use the formulas in here: https://en.wikipedia.org/wiki/Circular_segment - specifically, we know "R", so we can pick a "theta" such that "h" is less than the tolerance, and convert the arc curve to a series of chords each spanning this small "theta" angle, which will be within this tolerance compared to the true arc.

In fact barring direct arc support in svg2polylines I'll probably just implement something like this when I'm generating my paths in the 1st place...

This doesn't work for ellipses though, ellipse arcs really suck - approximating them with bezier curves is probably the most practical way to deal with them. I don't need them for my personal use case, though (I do really need #3 though).

**Comment by Perondas** [comment]
I have looked into this a bit and have found a good solution here: https://github.com/BigBadaboom/androidsvg/blob/master/androidsvg/src/main/java/com/caverock/androidsvg/utils/SVGAndroidRenderer.java

I have implemented it here:
429df426914b6a289cc68e21783cc4dd1f7ed5c4

**Comment by dbrgn** [comment]
This is now released in 0.7.0, thanks @Perondas!
