### ISSUE TITLE
Make curve flattening parameter configurable

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/svg2polylines#3]
This would have to be added to the FFI version as well.

**Comment by orenbenkiki** [comment]
Any chance of this being merged? The library is perfect for a use case I have in mind, except for lacking control over the tolerance.

**Comment by dbrgn** [comment]
Oh, I overlooked that PR. I'll give it a look tonight.

**Comment by orenbenkiki** [comment]
Thanks!
